### ISSUE TITLE
Windows PowerShell Error

### ISSUE THREAD

**Issue by baotran-bryan** [lzybkr/PSReadLine#2927]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.IO.FileLoadException: Could not load file or assembly 'file:///D:\OneDrive\Documents\WindowsPowerShell\Modules\PSReadline\2.2.0\net461\Microsoft.PowerShell.PSReadLine.Polyfiller.dll' or one of its dependencies. The cloud file provider is not running. (Exception from HRESULT: 0x8007016A)
File name: 'file:///D:\OneDrive\Documents\WindowsPowerShell\Modules\PSReadline\2.2.0\net461\Microsoft.PowerShell.PSReadLine.Polyfiller.dll'
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

### Screenshot

![image](https://user-images.githubusercontent.com/6832747/138490593-00cb44c7-6aa1-4d8e-b9a5-ff5bd8f71c7f.png)

### Environment data

```console
PSReadLine: 2.2.0-beta1
PowerShell: 5.1.22000.65
OS: Microsoft Windows 10.0.22000
BufferWidth: 188
BufferHeight: 50
```

### Steps to reproduce

Open Windows Powershell

### Expected behavior

No exception

### Actual behavior

Show exception

**Comment by daxian-dbw** [comment]
This is a known issue and has been addressed in 2.2.0-beta3 release of PSReadLine. Please upgrade to use 2.2.0-beta3 with the latest 7.2.0-preview.9 PowerShell.
