### ISSUE TITLE
Unable to scroll down while using git on powershell using keyboard shortcut.

### ISSUE THREAD

**Issue by arshadpatel** [lzybkr/PSReadLine#3631]
### Prerequisites

- [ ] Write a descriptive title.
- [ ] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [ ] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.963
OS: Microsoft Windows 10.0.22621
Last 122 Keys

 PageUp PageDown PageDown PageUp PageUp PageUp PageUp PageUp Ctrl++ Ctrl++ Ctrl++ Ctrl++ Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace E : Enter
 g i Spacebar Backspace Backspace Backspace Backspace D : Enter
 R Backspace P r o n Backspace Backspace Backspace Backspace c d Spacebar p Backspace P r o j e c t s ? Backspace ? Backspace / P r o Backspace Backspace o r t l Backspace f o l i a Enter
 P r o Backspace Backspace Backspace c d Spacebar P r o j e c t s ? Backspace / P o r t f o l i o Enter
 g i t Spacebar s t a t u s Enter
 PageDown
```

### Exception
```
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

I just used Fn+ PageDown key and this happend.

### Environment data

```console
PS Version: 5.1.22621.963
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 172
BufferHeight: 9001
```

### Steps to reproduce

I was using git through powershell and I wanted to perform further operations but I was unable to see where to type so to scroll down the page I used shortcut which we basically use while using powershell i.e, Fn+PageDn and this happend.

### Expected behavior

Page Scroll Down

### Actual behavior

Throwing Exception "The parameter is in correct."

**Comment by daxian-dbw** [comment]
"Fn+PageDn" is not a default key binding in PSReadLine. Is that a custom key binding that you defined?
Also, the version of PSReadLine you are using is very old. Please upgrade to the latest 2.2.6 version and see if the issue persists. See https://github.com/PowerShell/PSReadLine#upgrading for details on how to upgrade.

**Comment by arshadpatel** [comment]
Upgraded to the latest 2.2.6 version and able to scroll down using "Ctrl + DnArrow"
Thank You @daxian-dbw
