### ISSUE TITLE
Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

### ISSUE THREAD

**Issue by VatthanachaiW** [lzybkr/PSReadLine#772]
Hi, I'm not sure this bug are fixed. I found this when I press [UpArrow] for select previous command and hit enter.
`
Last 200 Keys:
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace r o c k e t c h a t Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 DownArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 d p c l e r UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace r o c k e t c h a t Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
`

**Comment by lzybkr** [comment]
Which version of PSReadLine are you using?

**Comment by VatthanachaiW** [comment]
Sorry, I'm not sure. Because I use cmder tools with Powershell. but the PS version table is 

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  228

**Comment by lzybkr** [comment]
`Get-Module PSReadLine` will report the version number.

**Comment by ppulwey** [comment]
This morning I had the same issue. My version is

ModuleType Version    Name
---------- -------    ----
Script     1.2        PSReadline
